# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/300c4cd9-2379-4031-95de-c0c857973092";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/300c4cd9-2379-4031-95de-c0c857973092";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/.swapvol" =
    { device = "/dev/disk/by-uuid/300c4cd9-2379-4031-95de-c0c857973092";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/300c4cd9-2379-4031-95de-c0c857973092";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/300c4cd9-2379-4031-95de-c0c857973092";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8475-3245";
      fsType = "vfat";
    };

  fileSystems."/mnt/ADATA" =
    { device = "/dev/disk/by-uuid/e225e41c-6c81-4864-995c-79e71b6eb1f8";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
