# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
      kernelModules = [];
    };
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];

    # Use the systemd-boot EFI boot loader.
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/42ff5d52-931a-43b4-bffb-d087e63e58b1";
      fsType = "btrfs";
      options = ["subvol=rootfs"];
    };
    "/.swapvol" = {
      device = "/dev/disk/by-uuid/42ff5d52-931a-43b4-bffb-d087e63e58b1";
      fsType = "btrfs";
      options = ["subvol=swap"];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/E802-07EC";
      fsType = "vfat";
    };
    "/home" = {
      device = "/dev/disk/by-uuid/42ff5d52-931a-43b4-bffb-d087e63e58b1";
      fsType = "btrfs";
      options = ["subvol=home"];
    };
    "/nix" = {
      device = "/dev/disk/by-uuid/42ff5d52-931a-43b4-bffb-d087e63e58b1";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };
    "/partition-root" = {
      device = "/dev/disk/by-uuid/42ff5d52-931a-43b4-bffb-d087e63e58b1";
      fsType = "btrfs";
    };
    "/mnt/ADATA" = {
      device = "/dev/disk/by-uuid/e225e41c-6c81-4864-995c-79e71b6eb1f8";
      fsType = "btrfs";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
