# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "nvme"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/003943a6-9f54-4c2a-8860-84260337271e";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

    "/.swapvol" = {
      device = "/dev/disk/by-uuid/003943a6-9f54-4c2a-8860-84260337271e";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/E5D3-F069";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/home" = {
      device = "/dev/disk/by-uuid/003943a6-9f54-4c2a-8860-84260337271e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/003943a6-9f54-4c2a-8860-84260337271e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

    "/partition-root" = {
      device = "/dev/disk/by-uuid/003943a6-9f54-4c2a-8860-84260337271e";
      fsType = "btrfs";
    };

    "/storage" = {
      device = "/dev/disk/by-uuid/b915b6bb-90ef-4468-bd99-8f8e032d2d91";
      fsType = "btrfs";
      options = [ "subvol=storage" ];
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
